#!/usr/bin/env python3
"""
WARNING: This demo script has been generated by AI.

Comprehensive demo of the Video to WebP Converter.

This demo showcases every feature of the unified video_to_webp module through
7 focused sections:
    1. Basic Conversion           – simplest one-liner usage
    2. Custom Resolution & Quality – resizing and quality control
    3. Frame Capping              – limiting vs rendering all frames
    4. File Size Compression      – smart compression to hit a KB target
    5. Resize Modes               – pad vs crop vs stretch, upscale control
    6. Manual Timing Control      – overriding automatic timing preservation
    7. Class-Based Usage          – reusing VideoToWebPConverter for batch work
"""

import shutil
import os
import glob
import time
import logging

import av
from PIL import Image

from video_to_webp import convert_video_to_webp, VideoToWebPConverter

# Supported video formats to scan for in demo_inp/
SUPPORTED_FORMATS = ["*.webm", "*.mp4", "*.mov", "*.gif", "*.mkv"]

# ──────────────────────────── Helpers ────────────────────────────

def analyze_video_file(file_path):
    """Analyze a video file and print detailed information."""
    try:
        with av.open(file_path) as container:
            stream = container.streams.best("video")
            if stream is None:
                raise ValueError("The provided file has no video streams.")

            fps = float(stream.average_rate or stream.guessed_rate or 30.0)
            fps = max(fps, 1.0)

            total_frames = stream.frames
            if total_frames == 0:
                if container.duration and container.duration > 0:
                    total_frames = int((container.duration / 1_000_000) * fps)
                else:
                    total_frames = sum(1 for _ in container.demux(stream))
                    total_frames = max(total_frames - 1, 0)

            duration = 0.0
            if container.duration and container.duration > 0:
                duration = container.duration / 1_000_000
            elif stream.duration and stream.time_base:
                duration = float(stream.duration * stream.time_base)
            if duration == 0 and total_frames > 0:
                duration = total_frames / fps

            print(f"    📁 Source    : {os.path.basename(file_path)}")
            print(f"    ⏱️  Original : {total_frames} frames @ {fps:.1f} FPS ({duration:.3f}s)")
            print(f"    📐 Resolution: {stream.width}x{stream.height}")
            return total_frames, fps, duration
    except Exception as e:
        print(f"    ❌ Analysis failed: {e}")
        return None, None, None


def analyze_webp_output(file_path):
    """Analyze a WebP output file and print detailed information."""
    if not os.path.exists(file_path):
        print(f"    ❌ Output file not found: {file_path}")
        return False

    try:
        img = Image.open(file_path)
        size_bytes = os.path.getsize(file_path)

        print(f"    ✅ Output    : {os.path.basename(file_path)}")
        print(f"    📐 Resolution: {img.size[0]}x{img.size[1]}  |  Frames: {img.n_frames}  |  Size: {size_bytes:,} bytes ({size_bytes / 1024:.1f} KB)")
        print(f"    🎬 Format    : {img.format}, Animated: {img.is_animated}")

        if hasattr(img, 'info') and 'duration' in img.info:
            frame_dur = img.info['duration']
            eff_fps = 1000 / frame_dur if frame_dur > 0 else 0
            eff_dur = img.n_frames * frame_dur / 1000
            print(f"    🎯 Playback  : {eff_fps:.1f} FPS, {eff_dur:.3f}s duration")
        return True
    except Exception as e:
        print(f"    ❌ Output analysis failed: {e}")
        return False


def run_conversion(input_file, output_file, label="Converting", **kwargs):
    """Helper that times a conversion, prints results, and returns success."""
    print(f"    🔄 {label}...")
    start = time.time()
    success = convert_video_to_webp(input_file, output_file, **kwargs)
    elapsed = time.time() - start

    if success:
        print(f"    ⏱️  Done in {elapsed:.2f}s")
        analyze_webp_output(output_file)
    else:
        print(f"    ❌ Conversion failed after {elapsed:.2f}s")
    return success

# ──────────────────────────── Demo 1 ────────────────────────────

def demo_basic_conversion(input_files):
    """Demo 1: Basic conversion — simplest possible usage."""
    print("\n🟢 Demo 1: Basic Conversion")
    print("=" * 60)
    print("One-liner with all defaults: original resolution, Q40,")
    print("180-frame cap, automatic timing preservation.\n")

    ok = 0
    for i, f in enumerate(input_files, 1):
        print(f"  [{i}/{len(input_files)}]")
        analyze_video_file(f)
        if run_conversion(f, f"demo_out/basic_{i}.webp"):
            ok += 1
        print()

    print(f"  📊 Result: {ok}/{len(input_files)} successful")
    return ok > 0

# ──────────────────────────── Demo 2 ────────────────────────────

def demo_custom_resolution(input_files):
    """Demo 2: Custom resolution and quality settings."""
    print("\n🟡 Demo 2: Custom Resolution & Quality")
    print("=" * 60)
    print("Same input file converted at three different resolutions")
    print("and quality levels, with automatic timing preservation.\n")

    f = input_files[0]
    settings = [
        {"width": 128, "height": 128, "quality": 90, "tag": "128x128_Q90"},
        {"width": 256, "height": 256, "quality": 70, "tag": "256x256_Q70"},
        {"width": 512, "height": 512, "quality": 40, "tag": "512x512_Q40"},
    ]

    for s in settings:
        print(f"  📐 {s['width']}×{s['height']}  Quality: {s['quality']}")
        analyze_video_file(f)
        run_conversion(f, f"demo_out/resolution_{s['tag']}.webp",
                       width=s["width"], height=s["height"], quality=s["quality"])
        print()

# ──────────────────────────── Demo 3 ────────────────────────────

def demo_frame_capping(input_files):
    """Demo 3: Frame capping — limited vs unlimited frames."""
    print("\n🔵 Demo 3: Frame Capping")
    print("=" * 60)
    print("Compares the default 180-frame cap, a custom 60-frame cap,")
    print("and uncapped (all original frames) output.\n")

    f = input_files[0]

    configs = [
        ("Default cap (180 frames)", "cap_default", {}),
        ("Custom cap (60 frames max)", "cap_60", {"max_frames": 60}),
        ("No cap (all frames)", "cap_none", {"frame_cap": False}),
    ]

    for label, tag, kwargs in configs:
        print(f"  🎞️  {label}")
        analyze_video_file(f)
        run_conversion(f, f"demo_out/frames_{tag}.webp", **kwargs)
        print()

# ──────────────────────────── Demo 4 ────────────────────────────

def demo_file_size_compression(input_files):
    """Demo 4: Smart compression to hit a file-size target."""
    print("\n🟠 Demo 4: File Size Compression")
    print("=" * 60)
    print("Automatically adjusts quality and frame count to stay")
    print("under a target file size. Tests strict and fast modes.\n")

    f = input_files[0]

    configs = [
        ("Target ≤ 256 KB (strict)", "256kb_strict",
         {"max_size": 256, "compress_faster": False}),
        ("Target ≤ 256 KB (fast)", "256kb_fast",
         {"max_size": 256, "compress_faster": True}),
        ("Target ≤ 64 KB (strict)", "64kb_strict",
         {"max_size": 64, "compress_faster": False}),
    ]

    for label, tag, kwargs in configs:
        print(f"  📦 {label}")
        analyze_video_file(f)
        run_conversion(f, f"demo_out/compress_{tag}.webp", **kwargs)
        print()

# ──────────────────────────── Demo 5 ────────────────────────────

def demo_resize_modes(input_files):
    """Demo 5: Resize modes — pad, crop, stretch, no-upscale."""
    print("\n🟣 Demo 5: Resize Modes")
    print("=" * 60)
    print("Demonstrates how aspect ratio, padding/cropping, and")
    print("upscale control affect the output.\n")

    f = input_files[0]

    configs = [
        ("Pad (default) — fit inside 256×128, pad transparent",
         "pad",
         {"width": 256, "height": 128, "keep_aspect": True, "pad": True}),
        ("Crop — cover 256×128, center-crop overflow",
         "crop",
         {"width": 256, "height": 128, "keep_aspect": True, "pad": False}),
        ("Stretch — ignore aspect ratio",
         "stretch",
         {"width": 256, "height": 128, "keep_aspect": False}),
        ("No upscale — clamp to original if target is larger",
         "no_upscale",
         {"width": 1024, "height": 1024, "allow_upscale": False}),
    ]

    for label, tag, kwargs in configs:
        print(f"  🎨 {label}")
        analyze_video_file(f)
        run_conversion(f, f"demo_out/resize_{tag}.webp", **kwargs)
        print()

# ──────────────────────────── Demo 6 ────────────────────────────

def demo_manual_timing(input_files):
    """Demo 6: Manual timing — override automatic FPS preservation."""
    print("\n🔴 Demo 6: Manual Timing Control")
    print("=" * 60)
    print("Disables automatic timing preservation and applies")
    print("a custom FPS, changing the playback speed.\n")

    f = input_files[0]
    analyze_video_file(f)

    for fps in [10, 30, 60]:
        print(f"  🎯 Manual FPS: {fps}")
        run_conversion(f, f"demo_out/timing_fps_{fps}.webp",
                       fps=fps, preserve_timing=False)
        print()

# ──────────────────────────── Demo 7 ────────────────────────────

def demo_class_usage(input_files):
    """Demo 7: Class-based usage for batch conversion."""
    print("\n⚪ Demo 7: Class-Based Batch Usage")
    print("=" * 60)
    print("Creates a VideoToWebPConverter instance once and reuses it")
    print("to convert all input files with identical settings.\n")

    converter = VideoToWebPConverter(
        width=512,
        height=512,
        quality=70,
        max_size=512,
        preserve_timing=True,
    )
    print("  📝 Converter: 512×512, Q70, ≤512 KB, timing preserved\n")

    ok = 0
    for i, f in enumerate(input_files, 1):
        print(f"  [{i}/{len(input_files)}]")
        analyze_video_file(f)

        out = f"demo_out/class_{i}.webp"
        print(f"    🔄 Converting...")
        start = time.time()
        success = converter.convert(f, out)
        elapsed = time.time() - start

        if success:
            print(f"    ⏱️  Done in {elapsed:.2f}s")
            analyze_webp_output(out)
            ok += 1
        else:
            print(f"    ❌ Conversion failed")
        print()

    print(f"  📊 Result: {ok}/{len(input_files)} successful")

# ──────────────────────────── Main ──────────────────────────────

def main():
    # Silence the module's internal logging to keep demo output clean.
    # The module logs at INFO level; set it to WARNING so only errors/warnings show.
    logging.getLogger("video_to_webp").setLevel(logging.WARNING)

    print("🎬 Video to WebP Converter — Comprehensive Demo")
    print("=" * 60)
    print("Showcasing all features of the unified video_to_webp module.\n")

    # Discover input files
    input_files = []
    for fmt in SUPPORTED_FORMATS:
        input_files.extend(glob.glob(f"demo_inp/{fmt}"))
    input_files = sorted(input_files)

    if not input_files:
        print("❌ No video files found in demo_inp/")
        print("   Please add some video files to demo_inp/ and run again.")
        return

    print(f"📁 Found {len(input_files)} video files in demo_inp/:")
    for f in input_files:
        print(f"   • {os.path.basename(f)}")

    # Clean output directory
    print("\n🧹 Clearing previous demo outputs...")
    if os.path.exists("demo_out"):
        shutil.rmtree("demo_out")
    os.makedirs("demo_out", exist_ok=True)

    # ── Run all demos ──
    try:
        demo_basic_conversion(input_files)
        demo_custom_resolution(input_files)
        demo_frame_capping(input_files)
        demo_file_size_compression(input_files)
        demo_resize_modes(input_files)
        demo_manual_timing(input_files)
        demo_class_usage(input_files)

        # ── Final Summary ──
        print("\n\n🎉 Demo Complete!")
        print("=" * 60)

        output_files = sorted(glob.glob("demo_out/*.webp"))
        if output_files:
            print(f"\n📋 Generated {len(output_files)} WebP files:\n")
            total = 0
            for f in output_files:
                sz = os.path.getsize(f)
                total += sz
                print(f"   • {os.path.basename(f):40s}  {sz:>8,} bytes  ({sz/1024:>7.1f} KB)")
            print(f"\n   Total: {total:,} bytes ({total/1024:.1f} KB)")

        print("\n✅ Key takeaways:")
        print("   • One module, one import — all features via parameters")
        print("   • convert_video_to_webp() for quick one-off conversions")
        print("   • VideoToWebPConverter class for batch / reusable workflows")
        print("   • Smart compression (max_size) keeps files under your limit")
        print("   • Full resize control: pad, crop, stretch, no-upscale")

        print("\n💡 Quick start:")
        print("   from video_to_webp import convert_video_to_webp")
        print("   convert_video_to_webp('input.mp4', 'output.webp')")

    except Exception as e:
        print(f"\n❌ Demo failed with error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
